# Site settings
site: derhansen.blog
title: A TechBlog by Torben Hansen
keywords: derhansen, blog, typo3
description: >-
  A TechBlog by Torben Hansen
lang: en-US
timezone:  Europe/Berlin

# Author settings
author:
  name: Torben Hansen
  bio: Freelance Full Stack Web Developer located in Germany. <br> I create web applications mainly using TYPO3, PHP, Python and JavaScript.
  picture: assets/images/profile.jpg 
  email: torben@derhansen.com


# URL settings
url: "https://www.derhansen.de"
permalink: pretty

lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

webrick:
  headers:
    Access-Control-Allow-Origin: "*"

exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false
theme: jekyll-theme-minimal